OS_RELEASE_FIELDS += "GITVERSION_BRANCHVERSION"
GITVERSION_BRANCHVERSION = "${GitVersion_BranchVersion}"

#TODO rename ICS_DM_IOTEDGE_YOCTO_VERSION
OS_RELEASE_FIELDS += "ICS_DM_IOTEDGE_YOCTO_VERSION"
