require conf/machine/include/rpi.inc
require conf/machine/include/rpi-pstore.inc

# adu compatibility id
# Note:
#  with wrynose the devel image needed a bigger rootfs making the image
#  incompatible with the scarthgap images => no update scarthgap -> wrynose
#  possible
OMNECT_ADU_DEVICEPROPERTIES_COMPATIBILITY_ID = "${@bb.utils.contains('OMNECT_RELEASE_IMAGE', '1', '4', '5', d)}"

# wic: how to partition
WKS_FILE = "omnect-os.rpi4.wks.in"

# u-boot boot cmd config vars
UBOOT_ARCH = "arm64"

# with transition to wrynose the devel image rootfs needed to be enlarged
OMNECT_PART_SIZE_ROOTFS ?= "${@bb.utils.contains('OMNECT_RELEASE_IMAGE', '1', '760832', '900000', d)}"
