#!/bin/bash

#
# optionally provide flashing whole disk image in INITRAMFS context
#

# Flash Mode
#     1    clone disk image from active block device to other one
#
OMNECT_FLASH_MODE=""

OMNECT_FLASH_MODE_VAR="flash-mode"
OMNECT_FLASH_DEVPATH_VAR="flash-mode-devpath"

# variable templates, which are replaced at build time
OMNECT_FLASH_MODE_BOOTLOADER_START="UNDEFINED"  # optionally, start of bootloader area
OMNECT_FLASH_MODE_UBOOT_ENV1_START="UNDEFINED"  # start of  first u-boot environment
OMNECT_FLASH_MODE_UBOOT_ENV2_START="UNDEFINED"  # start of second u-boot environment
OMNECT_FLASH_MODE_UBOOT_ENV_SIZE="UNDEFINED"    # size of u-boot environment
OMNECT_FLASH_MODE_DATA_SIZE="UNDEFINED"         # initial size of data partition (in KB)

# called by generic INITRAMFS
flash_mode_1_enabled() {
    debug "flash mode 1: ${OMNECT_FLASH_MODE} - ${OMNECT_FLASH_MODE_VAR}"

    # flash mode triggered at runtime
    OMNECT_FLASH_MODE=$(get_bootloader_env_var ${OMNECT_FLASH_MODE_VAR})
    if [ "${OMNECT_FLASH_MODE}" == "1" ] && [ -n "${OMNECT_FLASH_MODE_VAR}" ]; then
        return 0  # enable flash mode; call main entry point
    fi

    return 1  # disable flash mode; normal boot; main entry point _NOT_ called
}

get_start_sector()
{
    local part_dev="$(readlink -f $1)"

    sfdisk -d $(readlink -f /dev/omnect/rootblk) | \
        sed -n "s|^${part_dev}.*start=[[:space:]]\+\([[:digit:]]\+\),.*$|\1|p"
}

# clone active disk image to other block device
run_flash_mode_1() {
    local blk_dev_dst=""
    local blk_dev_src=""
    local data_partition=""
    local data_partition_size=""
    local data_partition_start=""
    local efi_entries=""
    local extended_partition=""
    local extended_partition_size=""
    local extended_partition_start=""
    local last_lba=""
    local machine_features=""
    local p=""
    local part_type=""
    local rootfs_bootpart=""

    echo "Entering omnect flashing mode 1 ..."

    # detect destination block device from environment variable
    blk_dev_dst=$(get_bootloader_env_var ${OMNECT_FLASH_DEVPATH_VAR} | cut -d= -f2)
    blk_dev_dst=$(readlink -f ${blk_dev_dst})

    # disable flash mode for subsequent restarts
    set_bootloader_env_var ${OMNECT_FLASH_MODE_VAR}
    set_bootloader_env_var ${OMNECT_FLASH_DEVPATH_VAR}

    # check for (mandatory) substitutions of variable templates
    if [ "${OMNECT_FLASH_MODE_UBOOT_ENV1_START}" == "UNDEFINED" ]; then stderr_fatal "missing definition OMNECT_FLASH_MODE_UBOOT_ENV1_START"; return 1; fi
    if [ "${OMNECT_FLASH_MODE_UBOOT_ENV2_START}" == "UNDEFINED" ]; then stderr_fatal "missing definition OMNECT_FLASH_MODE_UBOOT_ENV2_START"; return 1; fi
    if [ "${OMNECT_FLASH_MODE_UBOOT_ENV_SIZE}"   == "UNDEFINED" ]; then stderr_fatal "missing definition OMNECT_FLASH_MODE_UBOOT_ENV_SIZE"; return 1; fi
    if [ "${OMNECT_FLASH_MODE_DATA_SIZE}"        == "UNDEFINED" ]; then stderr_fatal "missing definition OMNECT_FLASH_MODE_DATA_SIZE"; return 1; fi

    if [ -z "${blk_dev_dst}" ]; then
        stderr_fatal "bootloader environment variable \"${OMNECT_FLASH_DEVPATH_VAR}\" not set"
        return 1
    fi
    for i in $(seq 1 30); do
        if [ -b "${blk_dev_dst}" ]; then break; fi
        echo "WAITING FOR destination block device \"${blk_dev_dst}\"..."
        sleep 1
    done
    if [ ${i} -eq 30 ]; then
        stderr_fatal "cannot find destination block device \"${blk_dev_dst}\""
        return 1
    fi

    # detect source block device
    blk_dev_src=$(readlink -f /dev/omnect/rootblk)

    if [ ! -b "${blk_dev_src}" ]; then stderr_fatal "${blk_dev_src} does not exist or not a block device"; return 1; fi

    if [ "${blk_dev_dst}" == "${blk_dev_src}" ]; then
        stderr_fatal "identical source and destination: \"${blk_dev_dst}\""
        return 1
    fi

    data_partition=$(get_block_device data)
    if [ -z "${data_partition}" ]; then
        stderr_fatal "cannot detect data partition"
        return 1
    fi
    # adapt size of data partition to initial value, before (optional) resize of data partition
    data_partition_size=$((OMNECT_FLASH_MODE_DATA_SIZE * 2)) # 1024 (yocto) -> 512 (sfdisk)

    # check for partition type
    part_type=$(get_partition_type)
    if [ "${part_type}" = "gpt" ]; then
        echo "DUMP gpt / partition table..."
        data_partition_start=$(get_start_sector ${data_partition})
        last_lba=$((data_partition_start+data_partition_size-1))
        sfdisk --dump "${blk_dev_src}" | \
        sed "s|^last-lba: \(.*\)$|last-lba: ${last_lba}|g" | \
        sed "s|\(^${data_partition}.*size=[[:space:]]\+\)\([[:digit:]]\+,\)\(.*\)$|\1 ${data_partition_size}, \3|g" >/tmp/sfdisk.txt
    elif [ "${part_type}" = "dos" ]; then
        echo "DUMP mbr / partition table..."
        extended_partition=$(readlink -f /dev/omnect/extended)
        if [ -z "${extended_partition}" ]; then
            stderr_fatal "cannot detect extended partition"
            return 1
        fi
        # calculate size of extended partition, not affected by (optional) resize of data partition
        extended_partition_start=$(get_start_sector $(get_block_device extended))
        data_partition_start=$(get_start_sector ${data_partition})
        extended_partition_size=$((data_partition_start - extended_partition_start + data_partition_size))
        if [ -z "${extended_partition_size}" ]; then
            stderr_fatal "cannot detect extended partition size"
            return 1
        fi

        sfdisk --dump "${blk_dev_src}" | \
        sed "s|\(^${data_partition}.*size=[[:space:]]\+\)\([[:digit:]]\+,\)\(.*\)$|\1 ${data_partition_size}, \3|g" | \
        sed "s|\(^${extended_partition}.*size=[[:space:]]\+\)\([[:digit:]]\+,\)\(.*\)$|\1 ${extended_partition_size}, \3|g" >/tmp/sfdisk.txt
    else
        stderr_fatal "unhandled partition type: \"${part_type}\""
        return 1
    fi

    echo "######## cloning disk: ${blk_dev_src} -> ${blk_dev_dst} ########"
    cat /tmp/sfdisk.txt
    run_cmd_stdout "sfdisk ${blk_dev_dst} </tmp/sfdisk.txt"
    # -- after sfdisk, the new partitions are available --

    # do we need partition handling?
    # eg root=/dev/sda2 -> rootblk=/dev/sda vs root=/dev/mmcblk1p2 -> rootblk=/dev/mmcblk1
    if [ ! -b "${blk_dev_dst}1" ]; then
        p="p"
    fi

    echo "CHECK for new partition scheme.."
    if [ ! -b "${blk_dev_dst}${p}1" ]; then stderr_fatal "\"${blk_dev_dst}${p}1\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}2" ]; then stderr_fatal "\"${blk_dev_dst}${p}2\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}3" ]; then stderr_fatal "\"${blk_dev_dst}${p}3\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}4" ]; then stderr_fatal "\"${blk_dev_dst}${p}4\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}5" ]; then stderr_fatal "\"${blk_dev_dst}${p}5\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}6" ]; then stderr_fatal "\"${blk_dev_dst}${p}6\" is not a block device"; return 1; fi
    if [ ! -b "${blk_dev_dst}${p}7" ]; then stderr_fatal "\"${blk_dev_dst}${p}7\" is not a block device"; return 1; fi
    if [ "${part_type}" = "dos" ]; then
        if [ ! -b "${blk_dev_dst}${p}8" ]; then stderr_fatal "\"${blk_dev_dst}${p}8\" is not a block device"; return 1; fi
    fi

    # handle u-boot not stored inside the boot partition
    # e.g. not UNDEFINED if BOOTLOADER_SEEK is set (phytec boards)
    if [ "${OMNECT_FLASH_MODE_BOOTLOADER_START}" != "UNDEFINED" ]; then
        echo "COPY u-boot..."
        run_cmd_stdout dd if=${blk_dev_src} iflag=skip_bytes skip=$((OMNECT_FLASH_MODE_BOOTLOADER_START*1024)) \
                          of=${blk_dev_dst} oflag=seek_bytes seek=$((OMNECT_FLASH_MODE_BOOTLOADER_START*1024)) \
                          bs=1024 count=$((OMNECT_FLASH_MODE_UBOOT_ENV1_START - OMNECT_FLASH_MODE_BOOTLOADER_START)) || return 1
    fi

    # enforce first boot condition
    echo "MKFS etc and data..."
    if [ "${part_type}" = "gpt" ]; then
        check_ext4_fs "etc"  "${blk_dev_dst}${p}6" 1
        check_ext4_fs "data" "${blk_dev_dst}${p}7" 1
    elif [ "${part_type}" = "dos" ]; then
        check_ext4_fs "etc"  "${blk_dev_dst}${p}7" 1
        check_ext4_fs "data" "${blk_dev_dst}${p}8" 1
    fi

    echo "COPY boot, factory and cert..."
    run_cmd_stdout dd if=/dev/omnect/boot    of="$(readlink -f ${blk_dev_dst}${p}1)" bs=10M || return 1
    if [ "${part_type}" = "gpt" ]; then
        run_cmd_stdout dd if=/dev/omnect/factory of="$(readlink -f ${blk_dev_dst}${p}4)" bs=10M || return 1
        run_cmd_stdout dd if=/dev/omnect/cert    of="$(readlink -f ${blk_dev_dst}${p}5)" bs=10M || return 1
    elif [ "${part_type}" = "dos" ]; then
        run_cmd_stdout dd if=/dev/omnect/factory of="$(readlink -f ${blk_dev_dst}${p}5)" bs=10M || return 1
        run_cmd_stdout dd if=/dev/omnect/cert    of="$(readlink -f ${blk_dev_dst}${p}6)" bs=10M || return 1
    fi

    echo "COPY current rootfs to rootfsA..."
    run_cmd_stdout e2image -ra -p "/dev/omnect/rootCurrent" "$(readlink -f ${blk_dev_dst}${p}2)" || return 1

    echo "ENFORCE default bootloader environment..."
    # Warning: we enforce  here that there is a redundant uboot env available, even if the initial wic did'nt have one
    dd if=/dev/zero bs=1024 count=${OMNECT_FLASH_MODE_UBOOT_ENV_SIZE} 2>/dev/null | tr "\000" "\377" >/tmp/uboot_env_ff.img
    run_cmd_stdout dd if=/tmp/uboot_env_ff.img of="${blk_dev_dst}" oflag=seek_bytes seek=$((OMNECT_FLASH_MODE_UBOOT_ENV1_START*1024)) || return 1
    run_cmd_stdout dd if=/tmp/uboot_env_ff.img of="${blk_dev_dst}" oflag=seek_bytes seek=$((OMNECT_FLASH_MODE_UBOOT_ENV2_START*1024)) || return 1

    machine_features=$(grep ^MACHINE_FEATURES= /etc/os-release | awk -F'"' '{print $2}')
    if [[ " ${machine_features} " =~ " grub " ]]; then
        echo "Configuring grub"
        run_cmd_stdout mkdir -p /tmp/boot
        run_cmd_stdout mount ${blk_dev_dst}${p}1 /tmp/boot
        sed "s#@@ROOT_DEVICE@@#${blk_dev_dst}${p}#g" /etc/omnect/grub.cfg.in > /tmp/boot/EFI/BOOT/grub.cfg
        run_cmd_stdout umount /tmp/boot
    fi

    if [[ " ${machine_features} " =~ " efi " ]]; then
        echo "Configuring efi"
        run_cmd_stdout efibootmgr --create --disk ${blk_dev_dst} --part 1 --label "omnect_os" --loader \\\\EFI\\\\BOOT\\\\bootx64.efi || return 1
        # delete all efi entries but last
        efi_entries=$(efibootmgr | grep ^Boot[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]\* | awk '{print $1}'| sed  '$ d')
        for i in ${efi_entries}; do
            i=${i#Boot}
            i=${i%\*}
            run_cmd_stdout efibootmgr --bootnum ${i} --delete-bootnum || return 1
        done
    fi

    echo "flash mode 1 successfully finished"
    run_cmd_stdout sync
    return 0
}

# main entry point
flash_mode_1_run() {
    add_module_post_hook on_exit
    set -o pipefail
    local blk_dev_data=""

    run_flash_mode_1 2>&1 | tee /tmp/flash-mode-1.log >/dev/console 2>&1;
    return=${?}
    blk_dev_data=$(get_block_device data)
    if [ -b "${blk_dev_data}" ]; then
        # store log file
        mkdir -p /tmp/mnt_data
        check_ext4_fs "data" "${blk_dev_data}" 0
        mount_partition "ext4" "${blk_dev_data}" "/tmp/mnt_data" "defaults,rw"
        run_cmd cp /tmp/flash-mode-1.log "/tmp/mnt_data"
        run_cmd sync
        run_cmd umount "/tmp/mnt_data"
    fi
    if [ ${return} -eq 0 ]; then poweroff -f; fi
}
