#!/bin/bash

#
# optionally provide flashing whole disk image in INITRAMFS context
#

# Flash Mode
#     2    flash disk image from network to active block device
#
OMNECT_FLASH_MODE=""
OMNECT_FLASH_MODE_FLAG_FILE="/etc/enforce_flash_mode"

# called by generic INITRAMFS
flash_mode_2_enabled() {
    debug "flash mode 2: ${OMNECT_FLASH_MODE}"

    # flag file (part of "omnect-os-initramfs-test")
    if [ -f ${OMNECT_FLASH_MODE_FLAG_FILE} ]; then
        msg "enable flash mode: by ${OMNECT_FLASH_MODE_FLAG_FILE}"
        OMNECT_FLASH_MODE=2
        return 0  # enable flash mode; call main entry point
    fi

    # flash mode triggered at runtime
    OMNECT_FLASH_MODE=$(get_bootloader_env_var flash-mode)
    if [ "${OMNECT_FLASH_MODE}" == "2" ]; then
        return 0  # enable flash mode; call main entry point
    fi

    return 1  # disable flash mode; normal boot; main entry point _NOT_ called
}

run_bmap_tool() {
    local umount_dev=""
    local bmap_ret=""

    # umount, if necessary
    mkdir -p /tmp
    cp /proc/mounts /tmp/all_mounts  # make snapshot
    while read umount_dev ignore; do
        if [[ ${umount_dev} =~ /${blkdev##*/} ]]; then
            echo "umount ${umount_dev}"
            umount ${umount_dev} 2>/dev/null
        fi
    done </tmp/all_mounts

    # bmap file must be copied with scp
    msg "please run  scp <your-bmap-file> omnect@${OMNECT_FLASH_MODE_IP_ADDR}:wic.bmap)"
    while true; do
        if [ -f /home/omnect/wic.bmap ] && [ $(lsof /home/omnect/wic.bmap | wc -l) -eq 0 ]; then break; fi
        sleep 1
    done
    msg "please run  scp <your-wic-image> omnect@${OMNECT_FLASH_MODE_IP_ADDR}:wic.xz)"
    while true; do
        if [ -f /home/omnect/wic.xz ]; then break; fi
        sleep 1
    done
    if [ ! -f ${OMNECT_FLASH_MODE_FLAG_FILE} ]; then
        run_cmd_stdout "echo \"${sha256}  /home/omnect/wic.xz\" | sha256sum -c" || return 1
    fi
    vfat_grub_dd_workaround "/dev/omnect/boot"
    export PATH
    run_cmd_stdout bmaptool copy --bmap /home/omnect/wic.bmap \
                                 /home/omnect/wic.xz /dev/omnect/rootblk;
    bmap_ret=$?
    if [ ${bmap_ret} -eq 0 ]; then return 0; fi  # success

    # bmaptool exited with error:
    #     - mismatch between bmap file and wic image
    #     - broken destination device
    #     - broken network
    #     - usually, there is no way to salvage
    msg_fatal "bmaptool failed: ${bmap_ret}" && return 1
}

vfat_grub_dd_workaround()
{
    local dest="${1}"
    local machine_features=$(grep ^MACHINE_FEATURES= /etc/os-release | awk -F'"' '{print $2}')

    # we encountered situations where the device could not boot after
    # flash-mode-2 and could boot if flash-mode-2 did run again.
    # it also could be fixed by manually copying the to be flashed
    # grub binary bootx64.efi again. (in the error case checksums
    # of bootx64.efi on the device and in the wic image differed.)

    # ATTENTION: this workaround makes it impossible to boot it
    # flash-mode-2 is not finished, e.g. device is shutdown waiting
    # for wic.bmap and wic.xz

    if [[ " ${machine_features} " =~ " grub " ]]; then
        dd if=/dev/zero of=${dest} bs=@@OMNECT_PART_SIZE_BOOT@@K count=1
    fi

}

# deploy WIC image via network to (same) active block device
run_flash_mode_2() {
    local sha256=$(get_bootloader_env_var flash-mode-sha256) || { msg_fatal "couldn't get \"flash-mode-sha256\""; return 1; }
    msg "Entering omnect flashing mode 2 ..."

    # disable flash mode for subsequent restarts
    set_bootloader_env_var flash-mode
    set_bootloader_env_var flash-mode-sha256

    # we already mounted /dev/omnect/boot when we're using grub. so we unmount before copying boot.
    if [ -f /usr/bin/grub-editenv ]; then
        sync
        run_cmd umount ${ROOTFS_DIR}/boot
    fi

    flash_mode_setup_network eth0 || return 1
    run_bmap_tool "${sha256}" || return 1
    flash_mode_efi_handling

    msg "Rebooting system..."
    sync
    run_cmd reboot -f
    # -- never reached --
}

# main entry point
flash_mode_2_run() {
    add_module_post_hook on_exit
    run_flash_mode_2
    return=${?}
    return=${?}
    echo flash_mode_2_run return=${return}
    return ${return}
}
