#!/bin/sh

imx_sdma_enabled() {
    return 0
}

imx_sdma_run() {
    # load imx_sdma as early as possible with firmware available
    mkdir -p /lib/firmware
    mkdir -p /lib/modules
    mount -o bind /rootfs/lib/modules /lib/modules
    mount -o bind /rootfs/lib/firmware /lib/firmware
    modprobe imx_sdma
    # umount deactivated on purpose: umount: can't unmount /lib/firmware: Device or resource busy
    # it isn't mounted in omnect-os anyway
    #umount /lib/firmware
    #umount /lib/modules
}
