#!/bin/sh

#
#  Setup files used to trigger factory reset and reboot
#

omnect_device_service_setup_enabled() {
    return 0
}

# get ID field from group file
get_id() {
    local name="$1"
    local file="$2"
    local line=""

    line=$(grep -E -e "^${name}:" ${file})
    if [ -z "${line}" ]; then echo ""; return; fi
    echo $line | awk -F: '{print $3}'
}

run_omnect_device_service_setup () {
    local tmp_dir="${ROOTFS_DIR}/run/omnect-device-service"  # /run is available in the INITRAMFS
    local factory_reset_trigger_file="${tmp_dir}/factory-reset-trigger"
    local factory_reset_restore_list="${tmp_dir}/factory-reset-restore-list"
    local reboot_trigger_file="${tmp_dir}/reboot-trigger"
    local omnect_device_service_group=""

    # get group ID
    omnect_device_service_group=$(get_id omnect_device_service ${ROOTFS_DIR}/etc/group)
    if [ -z "${omnect_device_service_group}" ]; then
        msg "ERROR: group omnect_device_service not found in rootfs"
        return 1
    fi

    # create files
    run_cmd mkdir -p ${tmp_dir} \
    && run_cmd touch ${factory_reset_trigger_file} \
    && run_cmd touch ${factory_reset_restore_list} \
    && run_cmd touch ${reboot_trigger_file} \
    && run_cmd chown root:${omnect_device_service_group} ${factory_reset_trigger_file} \
    && run_cmd chown root:${omnect_device_service_group} ${factory_reset_restore_list} \
    && run_cmd chown root:${omnect_device_service_group} ${reboot_trigger_file} \
    && run_cmd chmod 660 ${factory_reset_trigger_file} \
    && run_cmd chmod 660 ${factory_reset_restore_list} \
    && run_cmd chmod 660 ${reboot_trigger_file} \
    || return 1

    return 0
}

omnect_device_service_setup_run() {
    add_module_post_hook on_exit
    run_omnect_device_service_setup
    return=${?}
}
