#!/bin/sh

rootblk_dev_enabled() {
    return 0
}

rootblk_dev_run() {
    add_module_post_hook on_exit
    msg "$(grep ^PRETTY_NAME= /etc/os-release | cut -d= -f2) initramfs"
    rootblk_dev_generate_dev_omnect
    return=${?}
}
