#!/bin/sh

resize_data_enabled() {
    return 0
}

resize_data_run() {
    local resized_data=$(get_bootloader_env_var "resized-data")
    local ptype=$(get_partition_type)

    # data partition not yet resized
    if [ -z "${resized_data}" ]; then
        data_part=$(get_block_device data)
        [[ $(cat /proc/mounts | grep ${data_part} | wc -l) -ne 0 ]] && msg "error: resize_data: \"${data_part}\" is mounted." && return

        root_disk=${data_part%p*}
        data_part_nr=${data_part##*p}
        msg "omnect-os resize data partition: ${root_disk}p${data_part_nr}"

        if [ "${ptype}" = "gpt" ]; then
            sgdisk ${root_disk} -e
        elif [ "${ptype}" = "dos" ]; then
            [[ $(parted ${root_disk} print | grep extended | wc -l) -ne 1 ]] && msg "error: resize_data: couldn't determine extended partion" && return
            extended_part_nr=$(parted ${root_disk} print | grep extended | awk '{print $1}')
            parted ${root_disk} resizepart ${extended_part_nr} 100%
        else
            msg_fatal "unhandled partition type: \"${ptype}\"" && return 1
        fi

        parted ${root_disk} resizepart ${data_part_nr} 100%

        ln -sf /proc/self/mounts /etc/mtab
        e2fsck -y ${data_part}
        resize2fs -f ${data_part}
        sync

        # set resized_data in u-boot env
        set_bootloader_env_var resized-data 1
    fi
}
