#!/bin/sh

fs_mount_enabled() {
    return 0
}

fs_mount_run() {

    if [ -z "${ROOTFS_DIR}" ]; then
        fatal "no ROOTFS_DIR"
        return 1
    fi

    msg "ics-dm-os initramfs fs mount"

    # the comma separated option list is ordered; i.e., higher preference at the right hand side
    mnt_opts_default="defaults,noatime,nodiratime,async"

    setup_rootfs_partition "${ROOTFS_DIR}" "${mnt_opts_default},ro"
    insmod_overlayfs "${ROOTFS_DIR}"

    # mount cert
    cert_blk=$(get_block_device cert)
    check_ext4_fs "cert" "${cert_blk}" 0
    mount_partition "ext4" "${cert_blk}" "${ROOTFS_DIR}/mnt/cert" "${mnt_opts_default},rw"
    mkdir -p ${ROOTFS_DIR}/mnt/cert/ca
    mkdir -p ${ROOTFS_DIR}/mnt/cert/priv

    # mount factory
    factory_blk=$(get_block_device factory)
    mount_partition "ext4" "${factory_blk}" "${ROOTFS_DIR}/mnt/factory" "${mnt_opts_default},ro"

    setup_etc_partition "${ROOTFS_DIR}" "$(get_block_device etc)" "${mnt_opts_default},rw"

    # mount data partition
    #     mount flags can be optionally set via u-boot environment
    data_opts=$(get_bootloader_env_var "data-mount-options")
    if [ -n "${data_opts}" ]; then
        msg "note, bootloader variable data-mount-options set; going to use it"
    else
        data_opts="${mnt_opts_default},rw"
    fi
    setup_data_partition "${ROOTFS_DIR}" "$(get_block_device data)" "${data_opts}"

    # mount tmpfs
    mount -t tmpfs -o mode=0755,nodev,nosuid,strictatime tmpfs  ${ROOTFS_DIR}/run
    mount -t tmpfs -o defaults tmpfs  ${ROOTFS_DIR}/var/volatile
}
