#!/bin/sh

#
#  Setup systemd trigger file used by factory reset and reboot
#

icsdm_device_service_setup_enabled() {
    return 0
}

# get ID field from group file
get_id() {
    local name="$1"
    local file="$2"
    local line=""

    line=$(grep -E -e "^${name}:" ${file})
    if [ -z "${line}" ]; then echo ""; return; fi
    echo $line | awk -F: '{print $3}'
}

icsdm_device_service_setup_run() {
    local tmp_dir="${ROOTFS_DIR}/run/icsdm-device-service"  # /run is available in the INITRAMFS
    local factory_reset_trigger_file="${tmp_dir}/factory-reset-systemd-trigger"
    local factory_reset_restore_list="${tmp_dir}/factory-reset-restore-list"
    local reboot_trigger_file="${tmp_dir}/reboot-systemd-trigger"
    local icsdm_device_service_group=""

    # get group ID
    icsdm_device_service_group=$(get_id icsdm_device_service ${ROOTFS_DIR}/etc/group)
    if [ -z "${icsdm_device_service_group}" ]; then
        msg "ERROR: group icsdm_device_service not found in rootfs"
        return
    fi

    # create systemd trigger file
    run_cmd mkdir -p ${tmp_dir}
    run_cmd touch ${factory_reset_trigger_file}
    run_cmd touch ${factory_reset_restore_list}
    run_cmd touch ${reboot_trigger_file}
    run_cmd chown root:${icsdm_device_service_group} ${factory_reset_trigger_file}
    run_cmd chown root:${icsdm_device_service_group} ${factory_reset_restore_list}
    run_cmd chown root:${icsdm_device_service_group} ${reboot_trigger_file}
    run_cmd chmod 660 ${factory_reset_trigger_file}
    run_cmd chmod 660 ${factory_reset_restore_list}
    run_cmd chmod 660 ${reboot_trigger_file}
}
