#!/bin/sh

persistent_var_log_enabled() {
    return 0
}

persistent_var_log_run() {
    msg "ics-dm-os persistent var log"

    if [ -z "${ROOTFS_DIR}" ]; then
        fatal "no ROOTFS_DIR"
        return 1
    fi

    mkdir -p ${ROOTFS_DIR}/mnt/data/log
    mount -o bind ${ROOTFS_DIR}/mnt/data/log ${ROOTFS_DIR}/var/log
}
