#!/bin/sh

#
#  Setup systemd trigger file used by factory reset and reboot
#

remote_features_setup_enabled() {
    return 0
}

# get ID field from group file
get_id() {
    local name="$1"
    local file="$2"
    local line=""

    line=$(grep -E -e "^${name}:" ${file})
    if [ -z "${line}" ]; then echo ""; return; fi
    echo $line | awk -F: '{print $3}'
}

remote_features_setup_run() {
    local tmp_dir="${ROOTFS_DIR}/run/remote-features"  # /run is available in the INITRAMFS
    local factory_reset_trigger_file="${tmp_dir}/factory-reset-systemd-trigger"
    local factory_reset_restore_list="${tmp_dir}/factory-reset-restore-list"
    local reboot_trigger_file="${tmp_dir}/reboot-systemd-trigger"
    local remote_features_group=""

    # get group ID
    remote_features_group=$(get_id remote_features ${ROOTFS_DIR}/etc/group)
    if [ -z "${remote_features_group}" ]; then
        msg "ERROR: group remote_features not found in rootfs"
        return
    fi

    # create systemd trigger file
    run_cmd mkdir -p ${tmp_dir}
    run_cmd touch ${factory_reset_trigger_file}
    run_cmd touch ${factory_reset_restore_list}
    run_cmd touch ${reboot_trigger_file}
    run_cmd chown root:${remote_features_group} ${factory_reset_trigger_file}
    run_cmd chown root:${remote_features_group} ${factory_reset_restore_list}
    run_cmd chown root:${remote_features_group} ${reboot_trigger_file}
    run_cmd chmod 660 ${factory_reset_trigger_file}
    run_cmd chmod 660 ${factory_reset_restore_list}
    run_cmd chmod 660 ${reboot_trigger_file}
}
