#!/bin/sh

resize_data_enabled() {
    return 0
}

resize_data_run() {
    local data_part=$(readlink -f /dev/disk/by-label/data)

    # possibly resize data partition
    if [ "${bootparam_resize_data}" = "1" ]; then
        msg "ics-dm-os resize data partition"
        [[ $(cat /proc/mounts | grep ${data_part} | wc -l) -ne 0 ]] && echo "error: \"${data_part}\" is mounted." && exit 1

        root_disk=${data_part%p*}
        data_part_nr=${data_part##*p}
        [[ $(parted ${root_disk} print all | grep extended | wc -l) -ne 1 ]] && echo "error: couldn't determine extended partion" && exit 1
        extended_part_nr=$(parted ${root_disk} print all | grep extended | awk '{print $1}')

        parted ${root_disk} resizepart ${extended_part_nr} 100%
        parted ${root_disk} resizepart ${data_part_nr} 100%

        ln -sf /proc/self/mounts /etc/mtab

        # first boot: empty filesystem created by WIC, but enforce mkfs
        check_ext4_fs "data" "${data_part}" 1

        # set resized_data in u-boot env
        mkdir -p /boot
        mount -o defaults,rw /dev/disk/by-label/boot /boot
        fw_setenv resized_data 1
        umount /boot
    else
        # run fsck to handle unclean (not unmounted) state
        check_ext4_fs "data" "${data_part}" 0
    fi
}
