#!/bin/sh

resize_data_enabled() {
    return 0
}

resize_data_run() {
    # possibly resize data partition
    if [ "${bootparam_resize_data}" = "1" ]; then
        msg "ics-dm-os resize data partition"
        data_part=$(get_block_device data)
        [[ $(cat /proc/mounts | grep ${data_part} | wc -l) -ne 0 ]] && echo "error: \"${data_part}\" is mounted." && exit 1

        root_disk=${data_part%p*}
        data_part_nr=${data_part##*p}
        [[ $(parted ${root_disk} print all | grep extended | wc -l) -ne 1 ]] && echo "error: couldn't determine extended partion" && exit 1
        extended_part_nr=$(parted ${root_disk} print all | grep extended | awk '{print $1}')

        parted ${root_disk} resizepart ${extended_part_nr} 100%
        parted ${root_disk} resizepart ${data_part_nr} 100%

        ln -sf /proc/self/mounts /etc/mtab
        e2fsck -y ${data_part}
        resize2fs -f ${data_part}
        sync

        # set resized_data in u-boot env
        mkdir -p /boot
        boot_part=$(get_block_device boot)
        mount -o defaults,rw ${boot_part} /boot
        set_bootloader_env_var resized_data 1
        umount /boot
    fi
}
